//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReversoAPI.Web.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReversoAPI.Web.Tests.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; dir=&quot;ltr&quot;&gt;
        ///&lt;head&gt;&lt;title&gt;
        ///	Conjugation run | Conjugate verb run | Reverso Conjugator English
        ///&lt;/title&gt;&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;&lt;meta charset=&quot;utf-8&quot; /&gt;&lt;meta id=&quot;metaDescription&quot; name=&quot;description&quot; content=&quot;Conjugate the English verb run: indicative, past tense, participle, present perfect, gerund, conjugation models and irregular verbs. Translate run in context, with examples of use  and definition.&quot; /&gt;&lt;meta name=&quot;google&quot; value=&quot;notrans [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConjugationParseTestRunEng {
            get {
                return ResourceManager.GetString("ConjugationParseTestRunEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; dir=&quot;ltr&quot;&gt;
        ///&lt;head&gt;&lt;title&gt;
        ///	Conjugation бежать (I)  | Conjugate verb бежать (I)  Russian | Reverso Conjugator
        ///&lt;/title&gt;&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;&lt;meta charset=&quot;utf-8&quot; /&gt;&lt;meta id=&quot;metaDescription&quot; name=&quot;description&quot; content=&quot;Conjugate the Russian verb бежать (I) : indicative, past tense, participle, present perfect, gerund, conjugation models and irregular verbs. Translate бежать (I)  in context, with examples of use  and definition.&quot; /&gt;&lt;m [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConjugationParseTestRunRus {
            get {
                return ResourceManager.GetString("ConjugationParseTestRunRus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; dir=&quot;ltr&quot;&gt;
        ///
        ///&lt;head&gt;
        ///	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///	&lt;title&gt;folk | Synonyms and analogies for folk in English | Reverso Dictionary&lt;/title&gt;
        ///	&lt;link rel=&quot;preload&quot; href=&quot;//cdn.reverso.net/fonts/roboto/latin-n500.woff2&quot; as=&quot;font&quot; type=&quot;font/woff2&quot; crossorigin&gt;
        ///	&lt;link rel=&quot;preload&quot; href=&quot;https://cdn.reverso.net/syn/v40010/fonts/synonyms.woff2&quot; as=&quot;font&quot; type=&quot;font/woff2&quot;
        ///		crossorigin&gt;
        ///	&lt;link rel=&quot;preconnect&quot; crossorigin href=&quot;https://sd [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string folkSymonimsParseTest {
            get {
                return ResourceManager.GetString("folkSymonimsParseTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; dir=&quot;ltr&quot;&gt;
        ///
        ///&lt;head&gt;
        ///	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///	&lt;title&gt;hello - Translation into Russian - examples English | Reverso Context&lt;/title&gt;
        ///	&lt;meta name=&quot;description&quot;
        ///		content=&quot;Translations in context of &amp;quot;hello&amp;quot; in English-Russian from Reverso Context: say hello, hello kitty, to say hello to, saying hello, said hello&quot; /&gt;
        ///	&lt;link rel=&quot;alternate&quot; hreflang=&quot;en&quot; href=&quot;https://context.reverso.net/translation/english-russian/hell [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string helloParseTest {
            get {
                return ResourceManager.GetString("helloParseTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] spellingTestMoneyEng {
            get {
                object obj = ResourceManager.GetObject("spellingTestMoneyEng", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] translationTestConsienceEndRus {
            get {
                object obj = ResourceManager.GetObject("translationTestConsienceEndRus", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] translationTestPeaceEngRus {
            get {
                object obj = ResourceManager.GetObject("translationTestPeaceEngRus", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
