//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReversoAPI.Web.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReversoAPI.Web.Tests.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; dir=&quot;ltr&quot;&gt;
        ///&lt;head&gt;&lt;title&gt;
        ///	Conjugation run | Conjugate verb run | Reverso Conjugator English
        ///&lt;/title&gt;&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;&lt;meta charset=&quot;utf-8&quot; /&gt;&lt;meta id=&quot;metaDescription&quot; name=&quot;description&quot; content=&quot;Conjugate the English verb run: indicative, past tense, participle, present perfect, gerund, conjugation models and irregular verbs. Translate run in context, with examples of use  and definition.&quot; /&gt;&lt;meta name=&quot;google&quot; value=&quot;notrans [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Conjugation_Parse_Test_English {
            get {
                return ResourceManager.GetString("Conjugation_Parse_Test_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; dir=&quot;ltr&quot;&gt;
        ///&lt;head&gt;&lt;title&gt;
        ///	Conjugation לברוח | Conjugate verb לברוח Hebrew | Reverso Conjugator
        ///&lt;/title&gt;&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;&lt;meta charset=&quot;utf-8&quot; /&gt;&lt;meta id=&quot;metaDescription&quot; name=&quot;description&quot; content=&quot;Conjugate the Hebrew verb לברוח: indicative, past tense, participle, present, future, conjugation models, binyan. Translate לברוח in context, with examples of use  and definition.&quot; /&gt;&lt;meta name=&quot;google&quot; value=&quot;notranslate&quot; /&gt;&lt;meta  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Conjugation_Parse_Test_Hebrew {
            get {
                return ResourceManager.GetString("Conjugation_Parse_Test_Hebrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; dir=&quot;ltr&quot;&gt;
        ///&lt;head&gt;&lt;title&gt;
        ///	Conjugation 逃げる | Conjugate verb 逃げる Japanese | Reverso Conjugator
        ///&lt;/title&gt;&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;&lt;meta charset=&quot;utf-8&quot; /&gt;&lt;meta id=&quot;metaDescription&quot; name=&quot;description&quot; content=&quot;Conjugate the Japanese verb 逃げる: present, past, volitional, potential, conjugation models and irregular verbs. Translate 逃げる in context, with examples of use  and definition.&quot; /&gt;&lt;meta name=&quot;google&quot; value=&quot;notranslate&quot; /&gt;&lt;meta name=&quot;v [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Conjugation_Parse_Test_Japanese {
            get {
                return ResourceManager.GetString("Conjugation_Parse_Test_Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; dir=&quot;ltr&quot;&gt;
        ///&lt;head&gt;&lt;title&gt;
        ///	Conjugation cair | Conjugate verb cair Portuguese | Reverso Conjugator
        ///&lt;/title&gt;&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;&lt;meta charset=&quot;utf-8&quot; /&gt;&lt;meta id=&quot;metaDescription&quot; name=&quot;description&quot; content=&quot;Conjugate the Portuguese verb cair: particípio, pretérito, subjuntivo, futuro, see similar Portuguese verbs, irregular verbs, reflexive verbs. Translate cair in context, with examples of use  and definition.&quot; /&gt;&lt;meta name=&quot;google [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Conjugation_Parse_Test_Portuguese {
            get {
                return ResourceManager.GetString("Conjugation_Parse_Test_Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; dir=&quot;ltr&quot;&gt;
        ///&lt;head&gt;&lt;title&gt;
        ///	Conjugation бежать (I)  | Conjugate verb бежать (I)  Russian | Reverso Conjugator
        ///&lt;/title&gt;&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;&lt;meta charset=&quot;utf-8&quot; /&gt;&lt;meta id=&quot;metaDescription&quot; name=&quot;description&quot; content=&quot;Conjugate the Russian verb бежать (I) : indicative, past tense, participle, present perfect, gerund, conjugation models and irregular verbs. Translate бежать (I)  in context, with examples of use  and definition.&quot; /&gt;&lt;m [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Conjugation_Parse_Test_Russian {
            get {
                return ResourceManager.GetString("Conjugation_Parse_Test_Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; dir=&quot;ltr&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;/&gt;
        ///    &lt;title&gt;human - Translation into Arabic - examples English | Reverso Context&lt;/title&gt;
        ///&lt;meta name=&quot;description&quot; content=&quot;Translations in context of &amp;quot;human&amp;quot; in English-Arabic from Reverso Context: human rights, human beings, human being, human right, human race&quot; /&gt;
        ///&lt;link rel=&quot;alternate&quot; hreflang=&quot;en&quot; href=&quot;https://context.reverso.net/translation/english-arabic/human&quot; /&gt;&lt;link [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Context_Parse_Test_English_Arabic {
            get {
                return ResourceManager.GetString("Context_Parse_Test_English_Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; dir=&quot;ltr&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;/&gt;
        ///    &lt;title&gt;hello - Translation into Russian - examples English | Reverso Context&lt;/title&gt;
        ///&lt;meta name=&quot;description&quot; content=&quot;Translations in context of &amp;quot;hello&amp;quot; in English-Russian from Reverso Context: say hello, to say hello to, said hello, hello everyone, hello world&quot; /&gt;
        ///&lt;link rel=&quot;alternate&quot; hreflang=&quot;en&quot; href=&quot;https://context.reverso.net/translation/english-russian/hello&quot; / [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Context_Parse_Test_English_Russian {
            get {
                return ResourceManager.GetString("Context_Parse_Test_English_Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Spelling_API_Test_English {
            get {
                object obj = ResourceManager.GetObject("Spelling_API_Test_English", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; dir=&quot;ltr&quot;&gt;
        ///
        ///&lt;head&gt;
        ///	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///	&lt;title&gt;folk | Synonyms and analogies for folk in English | Reverso Dictionary&lt;/title&gt;
        ///	&lt;link rel=&quot;preload&quot; href=&quot;//cdn.reverso.net/fonts/roboto/latin-n500.woff2&quot; as=&quot;font&quot; type=&quot;font/woff2&quot; crossorigin&gt;
        ///	&lt;link rel=&quot;preload&quot; href=&quot;https://cdn.reverso.net/syn/v40010/fonts/synonyms.woff2&quot; as=&quot;font&quot; type=&quot;font/woff2&quot;
        ///		crossorigin&gt;
        ///	&lt;link rel=&quot;preconnect&quot; crossorigin href=&quot;https://sd [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Symonims_Parse_Test_English {
            get {
                return ResourceManager.GetString("Symonims_Parse_Test_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; dir=&quot;ltr&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///        &lt;title&gt;جمل | Synonyms and analogies for جمل in Arabic | Reverso Dictionary&lt;/title&gt;
        ///        	&lt;link rel=&quot;preload&quot; href=&quot;//cdn.reverso.net/fonts/roboto/latin-n500.woff2&quot; as=&quot;font&quot; type=&quot;font/woff2&quot; crossorigin&gt;
        ///        &lt;link rel=&quot;preload&quot; href=&quot;https://cdn.reverso.net/syn/v40010/fonts/synonyms.woff2&quot; as=&quot;font&quot; type=&quot;font/woff2&quot; crossorigin&gt;
        ///    &lt;link rel=&quot;preconnect&quot; crossori [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Synonim_Parse_Text_Arabic {
            get {
                return ResourceManager.GetString("Synonim_Parse_Text_Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; dir=&quot;ltr&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///        &lt;title&gt;איש | Synonyms and analogies for איש in Hebrew | Reverso Dictionary&lt;/title&gt;
        ///        	&lt;link rel=&quot;preload&quot; href=&quot;//cdn.reverso.net/fonts/roboto/latin-n500.woff2&quot; as=&quot;font&quot; type=&quot;font/woff2&quot; crossorigin&gt;
        ///        &lt;link rel=&quot;preload&quot; href=&quot;https://cdn.reverso.net/syn/v40010/fonts/synonyms.woff2&quot; as=&quot;font&quot; type=&quot;font/woff2&quot; crossorigin&gt;
        ///    &lt;link rel=&quot;preconnect&quot; crossori [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Synonims_Parse_Test_Herbew {
            get {
                return ResourceManager.GetString("Synonims_Parse_Test_Herbew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Translation_API_Test_Arabic_Hindi {
            get {
                object obj = ResourceManager.GetObject("Translation_API_Test_Arabic_Hindi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Translation_API_Test_English_Hebrew {
            get {
                object obj = ResourceManager.GetObject("Translation_API_Test_English_Hebrew", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Translation_API_Test_English_Korean {
            get {
                object obj = ResourceManager.GetObject("Translation_API_Test_English_Korean", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Translation_API_Test_English_Russian {
            get {
                object obj = ResourceManager.GetObject("Translation_API_Test_English_Russian", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Translation_API_Test_English_Russian_2_ {
            get {
                object obj = ResourceManager.GetObject("Translation_API_Test_English_Russian_2_", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
